mysite/mysite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),
]

mysite/polls/urls.py
from django.urls import path

from . import views

app_name = 'polls'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

mysite/polls/models.py
import datetime

from django.db import models
from django.utils import timezone


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now

    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Published recently?'

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

######################
class Person(models.Model):
    name = models.CharField(max_length=30)

    def __str__(self):
        return self.name

class Guest_list(models.Model):
    list_quests = []

    def __str__(self):
        return self.list_quests

mysite/polls/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.views import generic
from django.utils import timezone

from .models import Person, Guest_list


class IndexView(generic.ListView):
    template_name = 'partyICT4D/index.html'
    context_object_name = 'person_list'

    def get_queryset(self):
        return Guest_list.objects.order_by('-pub_date')[:5]

    def get_queryset(self):
        return Guest_list.objects.filter(
            pub_date__lte=timezone.now()
        ).order_by('-pub_date')[:5]


class DetailView(generic.DetailView):
    model = Guest_list
    template_name = 'partyICT4D/detail.html'

    def get_queryset(self):
        return Guest_list.objects.filter(pub_date__lte=timezone.now())


class ResultsView(generic.DetailView):
    model = Guest_list
    template_name = 'partyICT4D/results.html'


def add_people_to_list(request, person_id):
    person = get_object_or_404(Guest_list, pk=person_id)
    try:
        person_list = person.name.get(pk=request.POST['guest_list'])
    except (KeyError, Person.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'partyICT4D/detail.html', {
            # 'question': question,
            'error_message': "You didn't fill in your name",
        })
    else:
        person_list.append(person)
        person_list.save()
        return HttpResponseRedirect(reverse('partyICT4D:results', args=(person.id,)))






# class IndexView(generic.ListView):
#     template_name = 'polls/index.html'
#     context_object_name = 'latest_question_list'
#
#     def get_queryset(self):
#         return Question.objects.order_by('-pub_date')[:5]
#
#     def get_queryset(self):
#         return Question.objects.filter(
#             pub_date__lte=timezone.now()
#         ).order_by('-pub_date')[:5]
#
#
# class DetailView(generic.DetailView):
#     model = Question
#     template_name = 'polls/detail.html'
#
#     def get_queryset(self):
#         return Question.objects.filter(pub_date__lte=timezone.now())
#
#
# class ResultsView(generic.DetailView):
#     model = Question
#     template_name = 'polls/results.html'
#
# def vote(request, question_id):
#     question = get_object_or_404(Question, pk=question_id)
#     try:
#         selected_choice = question.choice_set.get(pk=request.POST['choice'])
#     except (KeyError, Choice.DoesNotExist):
#         # Redisplay the question voting form.
#         return render(request, 'polls/detail.html', {
#             'question': question,
#             'error_message': "You didn't select a choice.",
#         })
#     else:
#         selected_choice.votes += 1
#         selected_choice.save()
#         return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))
#


# class QuestionDetailViewTests(TestCase):
#     def test_future_question(self):
#         future_question = create_question(question_text='Future question.', days=5)
#         url = reverse('polls:detail', args=(future_question.id,))
#         response = self.client.get(url)
#         self.assertEqual(response.status_code, 404)
#
#     def test_past_question(self):
#         past_question = create_question(question_text='Past Question.', days=-5)
#         url = reverse('polls:detail', args=(past_question.id,))
#         response = self.client.get(url)
#         self.assertContains(response, past_question.question_text)

mysite/polls/templates/partyICT4D/detail.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}" />

<h1>Please Enter your Name</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'partyICT4D:person' quest_list.id %}" method="post">
{% csrf_token %}
{% for name in quest_list.all %}
    <label for="guest_list{{ forloop.counter }}">{{ name.text }}</label><br />
    <input type="text" name="person" id="guest_list{{ forloop.counter }}" value="please enter your name" />
{% endfor %}
<input type="submit" value="Enter" />
</form>

mysite/polls/templates/partyICT4D/index.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}" />

{% if guest_list =! [] %}
    <ul>
    {% for name in guest_list %}
        <li><a href="{% url 'detail' guest_list.id %}">{{ guest_list.text }}</a></li>    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

mysite/polls/templates/partyICT4D/results.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}" />

<h1>Quests of the Party ICT4D Party</h1>

<ul>
{% for name in quest_list.all %}
    <li>{{ name.text }}</li>
{% endfor %}
</ul>

<a href="{% url 'partyICT4D:detail' quest_list.id %}">Add someone else?</a>

mysite/polls/templates/polls/detail.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}" />

<h1>Please Enter your Name</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'polls:vote' question.id %}" method="post">
{% csrf_token %}
{% for choice in question.choice_set.all %}
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br />
    <input type="text" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" />
{% endfor %}
<input type="submit" value="Enter" />
</form>

mysite/polls/templates/polls/index.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}" />

{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
        <li><a href="{% url 'detail' question.id %}">{{ question.question_text }}</a></li>    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

mysite/polls/templates/polls/results.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}" />

<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Vote again?</a>